[package]
name = "engine_cache"
version = "0.1.0"
authors = ["eoiyxns <yi.a.song@ericsson.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lz4 = "1.23.1"
actix = "0.10.0-alpha.3"
actix-rt = "1.1"
log = "0.4"
