[package]
name = "io_controller"
version = "0.1.0"
authors = ["MissSummer <madamsummer@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
mio = "0.6.22"
